<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8608" started-at="2019-07-21T14:24:15Z" finished-at="2019-07-21T14:24:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8608" started-at="2019-07-21T14:24:15Z" finished-at="2019-07-21T14:24:24Z">
      <class name="com.hybridprofinal.test.VerifyLoginTest">
        <test-method status="PASS" signature="BrowserSetUp()[pri:0, instance:com.hybridprofinal.test.VerifyLoginTest@239963d8]" name="BrowserSetUp" is-config="true" duration-ms="2792" started-at="2019-07-21T19:54:15Z" finished-at="2019-07-21T19:54:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserSetUp -->
        <test-method status="FAIL" signature="VerifyLogin(java.lang.reflect.Method)[pri:0, instance:com.hybridprofinal.test.VerifyLoginTest@239963d8]" name="VerifyLogin" duration-ms="5042" started-at="2019-07-21T19:54:18Z" finished-at="2019-07-21T19:54:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.hybridprofinal.test.VerifyLoginTest.VerifyLogin(java.lang.reflect.Method) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.hybridprofinal.commonutility.Interaction.WaitForPageToLoad(Interaction.java:49)
	at com.hybridpro.pageobjects.LoginPage.VerifyLoginPage(LoginPage.java:32)
	at com.hybridprofinal.test.VerifyLoginTest.VerifyLogin(VerifyLoginTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogin -->
        <test-method status="PASS" signature="CleanUp()[pri:0, instance:com.hybridprofinal.test.VerifyLoginTest@239963d8]" name="CleanUp" is-config="true" duration-ms="681" started-at="2019-07-21T19:54:23Z" finished-at="2019-07-21T19:54:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CleanUp -->
      </class> <!-- com.hybridprofinal.test.VerifyLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
